# movie data web scraped from wikipedia for year 2018-2022 for movie recommendation

In [447]:
import pandas as pd
import numpy as np
import requests
from bs4 import BeautifulSoup
import ast

In [8]:
import config

In [11]:
# import os
# from dotenv import load_dotenv
# load_dotenv()

# API_KEY = os.getenv('movie_api')

In [448]:
class get_movie_data:
    
    def __init__(self,url):
        self.url = url
    
    def web_scrape(self):
        df = pd.DataFrame()
        webpage = requests.get(self.url).text
        soup = BeautifulSoup(webpage, 'lxml')
        table = soup.find_all('table', class_='wikitable sortable')
        for i in range(len(table)):
            df1 = pd.read_html(str(table[i]))[0]
            df = df.append(df1,ignore_index=True)
        return(df)

In [449]:

movie_df = pd.DataFrame()
#get data from 2018 to 2022
for i in range(2017,2023):
    url = f'https://en.wikipedia.org/wiki/List_of_American_films_of_{i}'
    data=get_movie_data(url)
    fin_df=data.web_scrape()
    
    movie_df = movie_df.append(fin_df,ignore_index=True)

In [450]:
movie_df = movie_df[['Title','Cast and crew']]

In [451]:
movie_df

,Title,Cast and crew
0,Underworld: Blood Wars,Anna Foerster (director); Cory Goodman (screen...
1,Arsenal,Steven C. Miller (director); Jason Mosberg (sc...
2,Between Us,Rafael Palacio Illingworth (director/screenpla...
3,Monster Trucks,Chris Wedge (director); Derek Connolly (screen...
4,The Bye Bye Man,Stacy Title (director); Jonathan Penner (scree...
...,...,...
1680,The Pale Blue Eye,Scott Cooper (director/screenplay); Christian ...
1681,Babylon,Damien Chazelle (director/screenplay); Brad Pi...
1682,NaN,NaN
1683,NaN,NaN
1684,NaN,NaN

In [452]:
movie_df[movie_df['Title'].isnull()]

     Title Cast and crew
1388   NaN           NaN
1611   NaN           NaN
1682   NaN           NaN
1683   NaN           NaN
1684   NaN           NaN

In [454]:
movie_df = movie_df.dropna(how='any')

In [455]:
movie_df = movie_df.reset_index(drop=True)

In [456]:
len(movie_df)

1680

In [458]:
movie_df  = movie_df.drop_duplicates(subset='Title', keep='last')

In [459]:
len(movie_df)

1676

In [460]:
movie_df = movie_df.reset_index(drop=True)

In [462]:
movie_df['director'] = [i.split('(director')[0] for i in movie_df['Cast and crew']]

In [491]:
movie_df['cast_crew'] = [[i for i in j.split(';') if 'director' not in i and 'screenplay' not in i] for j in movie_df['Cast and crew']]

In [492]:
#there are some values in Cast and crew which needs to be split at (';') inplace of (',')

In [501]:

for i in range(len(movie_df)) :
    if len(movie_df.loc[i]['cast_crew'])==0:
        movie_df.loc[i]['cast_crew'] = [i for i in  movie_df.loc[i]['Cast and crew'].split(',') if 'director' not in i and 'screenplay' not in i]

In [505]:
# movie_df

In [507]:
movie_df.isnull().sum()

Title            0
Cast and crew    0
director         0
cast_crew        0
dtype: int64

In [509]:
movie_df['cast_crew'] = movie_df['cast_crew'].apply(lambda x:" ".join(x))

In [510]:
movie_df

,Title,Cast and crew,director,cast_crew
0,Underworld: Blood Wars,Anna Foerster (director); Cory Goodman (screen...,Anna Foerster,"Kate Beckinsale, Theo James, Lara Pulver, Jam..."
1,Arsenal,Steven C. Miller (director); Jason Mosberg (sc...,Steven C. Miller,"Adrian Grenier, Johnathon Schaech, Nicolas Ca..."
2,Between Us,Rafael Palacio Illingworth (director/screenpla...,Rafael Palacio Illingworth,"Olivia Thirlby, Ben Feldman, Adam Goldberg, A..."
3,Monster Trucks,Chris Wedge (director); Derek Connolly (screen...,Chris Wedge,"Lucas Till, Jane Levy, Amy Ryan, Holt McCalla..."
4,The Bye Bye Man,Stacy Title (director); Jonathan Penner (scree...,Stacy Title,"Douglas Smith, Doug Jones, Michael Trucco, Cr..."
...,...,...,...,...
1671,I Wanna Dance with Somebody,Kasi Lemmons (director); Anthony McCarten (scr...,Kasi Lemmons,"Naomi Ackie, Ashton Sanders, Stanley Tucci"
1672,Wildcat,"Melissa Lesh, Trevor Frost (directors)","Melissa Lesh, Trevor Frost",Melissa Lesh
1673,Glass Onion: A Knives Out Mystery,Rian Johnson (director/screenplay); Daniel Cra...,Rian Johnson,"Daniel Craig, Edward Norton, Janelle MonÃ¡e, K..."
1674,The Pale Blue Eye,Scott Cooper (director/screenplay); Christian ...,Scott Cooper,"Christian Bale, Harry Melling, Gillian Anders..."
1675,Babylon,Damien Chazelle (director/screenplay); Brad Pi...,Damien Chazelle,"Brad Pitt, Margot Robbie, Diego Calva, Tobey ..."

In [22]:
#get genres for each movie

In [13]:
from tmdbv3api import TMDb
from tmdbv3api import Movie

In [14]:
tmdb = TMDb()
tmdb.api_key = config.MOVIE_API_KEY
tmdb.language = 'en'

In [15]:
genres = []

In [29]:
gnrs_url = f'https://api.themoviedb.org/3/genre/movie/list?api_key={tmdb.api_key}&language=en-US'
response = requests.get(gnrs_url).json()
genres = response['genres']

In [31]:
temp_df = pd.DataFrame(columns=['genres','id','Title'])
temp_df['Title'] = movie_df['Title']

tmdb_movie = Movie()
tmdb_movie.language='en'
for ind  in range(len(movie_df)):
    results=tmdb_movie.search(term=temp_df.loc[ind]['Title'])
    if results:

        if results[0]['genre_ids']:
            temp_df.loc[ind,'genres'] = results[0]['genre_ids']
        if results[0]['id']:
            temp_df.loc[ind,'id'] = results[0]['id']

In [524]:
temp_df[temp_df['Title']=='Wildcat']

               genres      id    Title
1673  [18, 53, 10752]  762735  Wildcat

In [512]:
movie_df = pd.merge(movie_df, temp_df, on='Title')

In [513]:
movie_df

,Title,Cast and crew,director,cast_crew,genres,id
0,Underworld: Blood Wars,Anna Foerster (director); Cory Goodman (screen...,Anna Foerster,"Kate Beckinsale, Theo James, Lara Pulver, Jam...","[14, 28, 53, 27]",346672
1,Arsenal,Steven C. Miller (director); Jason Mosberg (sc...,Steven C. Miller,"Adrian Grenier, Johnathon Schaech, Nicolas Ca...",[53],388202
2,Between Us,Rafael Palacio Illingworth (director/screenpla...,Rafael Palacio Illingworth,"Olivia Thirlby, Ben Feldman, Adam Goldberg, A...","[10749, 12, 18]",290512
3,Monster Trucks,Chris Wedge (director); Derek Connolly (screen...,Chris Wedge,"Lucas Till, Jane Levy, Amy Ryan, Holt McCalla...","[28, 35, 878]",262841
4,The Bye Bye Man,Stacy Title (director); Jonathan Penner (scree...,Stacy Title,"Douglas Smith, Doug Jones, Michael Trucco, Cr...","[27, 53]",292280
...,...,...,...,...,...,...
1672,I Wanna Dance with Somebody,Kasi Lemmons (director); Anthony McCarten (scr...,Kasi Lemmons,"Naomi Ackie, Ashton Sanders, Stanley Tucci","[18, 36]",696157
1673,Wildcat,"Melissa Lesh, Trevor Frost (directors)","Melissa Lesh, Trevor Frost",Melissa Lesh,"[18, 53, 10752]",762735
1674,Glass Onion: A Knives Out Mystery,Rian Johnson (director/screenplay); Daniel Cra...,Rian Johnson,"Daniel Craig, Edward Norton, Janelle MonÃ¡e, K...","[35, 80, 9648]",661374
1675,The Pale Blue Eye,Scott Cooper (director/screenplay); Christian ...,Scott Cooper,"Christian Bale, Harry Melling, Gillian Anders...","[80, 53, 9648, 27]",800815
1676,Babylon,Damien Chazelle (director/screenplay); Brad Pi...,Damien Chazelle,"Brad Pitt, Margot Robbie, Diego Calva, Tobey ...","[28, 12, 878, 53]",9381

In [514]:
movie_df.isnull().sum()

Title            0
Cast and crew    0
director         0
cast_crew        0
genres           5
id               2
dtype: int64

In [515]:
movie_df.dropna(inplace=True)

In [516]:
movie_df.isnull().sum()

Title            0
Cast and crew    0
director         0
cast_crew        0
genres           0
id               0
dtype: int64

In [517]:
movie_df = movie_df.reset_index(drop=True)

In [94]:
gen = {}
for item in genres:
    gen[item['id']] = item['name']

In [518]:
gen

{28: 'Action',
 12: 'Adventure',
 16: 'Animation',
 35: 'Comedy',
 80: 'Crime',
 99: 'Documentary',
 18: 'Drama',
 10751: 'Family',
 14: 'Fantasy',
 36: 'History',
 27: 'Horror',
 10402: 'Music',
 9648: 'Mystery',
 10749: 'Romance',
 878: 'Science Fiction',
 10770: 'TV Movie',
 53: 'Thriller',
 10752: 'War',
 37: 'Western'}

In [72]:
# gen_lst = movie_df['genres'].apply(lambda item_genres :{itm :value for (itm,value) in gen.items() if itm in item_genres})

In [519]:
movie_df['genres'] = movie_df['genres'].apply(lambda item :[gen[i] for i in  item])

In [520]:
movie_df['genres'] = movie_df['genres'].apply(lambda genres: " ".join(genres))

In [522]:
movie_df.to_csv('movie_2022.csv')

In [530]:
movie_df[movie_df['genres']=='Documentary']

,Title,Cast and crew,director,cast_crew,genres,id
21,I Am Not Your Negro,Raoul Peck (director/screenplay); Samuel L. Ja...,Raoul Peck,Samuel L. Jackson,Documentary,411019
78,Born in China,"Lu Chuan (director); David Fowler, Brian Leith...",Lu Chuan,John Krasinski (narrator),Documentary,355277
86,The Lovers,Azazel Jacobs (director/screenplay); Debra Win...,Azazel Jacobs,"Debra Winger, Tracy Letts, Aidan Gillen, Melo...",Documentary,65695
134,An Inconvenient Sequel: Truth to Power,"Bonni Cohen, Jon Shenk (director); Al Gore","Bonni Cohen, Jon Shenk",Al Gore,Documentary,432602
154,Served Like A Girl,Lysa Heslov (director),Lysa Heslov,,Documentary,438447
320,Pandas,"Drew Fellman, David Douglas (directors); Drew ...","Drew Fellman, David Douglas",Kristen Bell,Documentary,497802
350,Pope Francis: A Man of His Word,Wim Wenders (director); Pope Francis,Wim Wenders,Pope Francis,Documentary,505205
363,Won't You Be My Neighbor?,Morgan Neville (director); Fred Rogers,Morgan Neville,Fred Rogers,Documentary,490003
440,Fahrenheit 11/9,Michael Moore (director/screenplay),Michael Moore,,Documentary,532908
441,"Love, Gilda",Lisa Dapolito (director); Gilda Radner,Lisa Dapolito,Gilda Radner,Documentary,511972
450,The Great Buster: A Celebration,Peter Bogdanovich (director),Peter Bogdanovich,,Documentary,539199
678,Running with the Devil,Jason Cabell (director/screenplay); Nicolas Ca...,Jason Cabell,"Nicolas Cage, Laurence Fishburne",Documentary,1005342
688,Wrinkles the Clown,Michael Beach Nichols (director); Michael Beac...,Michael Beach Nichols,,Documentary,619262
849,Athlete A,"Bonni Cohen, Jon Shenk (director)","Bonni Cohen, Jon Shenk",Bonni Cohen,Documentary,684700
879,Boys State,"Amanda McBaine, Jesse Moss (directors)","Amanda McBaine, Jesse Moss",Amanda McBaine,Documentary,653723
1159,Rita Moreno: Just a Girl Who Decided to Go for It,Mariem PÃ©rez Riera (director/screenplay); Rita...,Mariem PÃ©rez Riera,"Rita Moreno, Eva Longoria, George Chakiris, G...",Documentary,776526
1161,Truman & Tennessee: An Intimate Conversation,Lisa Immordino Vreeland (director/screenplay);...,Lisa Immordino Vreeland,"Jim Parsons, Zachary Quinto",Documentary,730081
1164,A Crime on the Bayou,Nancy Buirski (director/screenplay); Gary Dunc...,Nancy Buirski,"Gary Duncan, Richard Sobol",Documentary,763040
1173,Fathom,Drew Xanthopoulos (director/screenplay); Miche...,Drew Xanthopoulos,"Michelle Fournet, Ellen Garland",Documentary,819024
1195,Roadrunner: A Film About Anthony Bourdain,Morgan Neville (director/screenplay); Caitrin ...,Morgan Neville,Anthony Bourdain,Documentary,642732
1204,Val,"Leo Scott, Ting Poo (directors); Val Kilmer","Leo Scott, Ting Poo",Val Kilmer,Documentary,834027
1205,Ailey,Jamila Wignot (director),Jamila Wignot,,Documentary,776519
1214,Enemies of the State,Sonia Kennebeck (director),Sonia Kennebeck,,Documentary,698495
1221,Homeroom,Peter Nicks (director),Peter Nicks,,Documentary,776523
1227,Not Going Quietly,Nicholas Bruckman (director/screenplay); Amand...,Nicholas Bruckman,,Documentary,736117
1262,Show Me the Father,"Rick Altizer (director); Sherman Smith, Tony E...",Rick Altizer,"Sherman Smith, Tony Evans, Steven Kendrick, A...",Documentary,858385
1279,My Name is Pauli Murray,"Betsy West, Julie Cohen (director); Talleah Br...","Betsy West, Julie Cohen",Betsy West Julie Cohen Betsy West,Documentary,776589
1307,"Introducing, Selma Blair",Rachel Fleit (director); Selma Blair,Rachel Fleit,Selma Blair,Documentary,795613
1461,Polar Bear,"Alastair Fothergill, Jeff Wilson (directors); ...","Alastair Fothergill, Jeff Wilson",Catherine Keener,Documentary,927070
1575,Flight/Risk,"Karim Amer, Omar Mullick (directors)","Karim Amer, Omar Mullick",Karim Amer,Documentary,1001869
1608,The Redeem Team,"Jon Weinbach (director); LeBron James, Dwyane ...",Jon Weinbach,"LeBron James, Dwyane Wade, Mike Krzyzewski",Documentary,1018648
1638,Is That Black Enough for You?!?,"Elvis Mitchell (director); Margaret Avery, Har...",Elvis Mitchell,"Margaret Avery, Harry Belafonte, Charles Burn...",Documentary,1013572

In [ ]:
# process followed in this notebook
# 1. Using url 'https://en.wikipedia.org/wiki/List_of_American_films_of_{year: (2018-2022)}' movie data is web scraped 
#    using beautifulsoup library .
# 2. Here only the information like cast crew and title of movies are extracted but for content based movie recommendation
#    system we need genres also.
# 3. Genres of all the movie extracted in above step are extracted using python library tmdbv3api through 
#    which we can hit the url 'https://api.themoviedb.org/3/genre/movie/list?api_key={tmdb.api_key}&language=en-US' 
#    to get the data in json format which is then converted into dataframe
# 4. In next step dataframe is exported into a csv file which is then imported into another notebook for
#    content based movie recommendation system